-- ============================================================ -- SISTEMA DE MENTORING - BASE DE DATOS POSTGRESQL -- ============================================================ 
-- Extensión para generación de UUID 
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
-- ============================================================ -- SECCIÓN: USUARIOS Y AUTENTICACIÓN -- ============================================================
CREATE TABLE usuario ( usuario_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), nombre VARCHAR(45), rol VARCHAR(20) );
-- ============================================================ -- SECCIÓN: CATÁLOGOS GENERALES -- ============================================================
CREATE TABLE carrera ( id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), nombre VARCHAR(45) );
CREATE TABLE tipo_archivo ( id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), nombre VARCHAR(45) );
CREATE TABLE modalidad_trabajo ( id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), nombre VARCHAR(45) );
CREATE TABLE area ( id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), nombre VARCHAR(20), padre_id UUID, esta_activo BOOLEAN, fecha_creacion DATE, fecha_actualizacion DATE, CONSTRAINT fk_area_padre FOREIGN KEY (padre_id) REFERENCES area(id) );
-- ============================================================ -- SECCIÓN: ADMINISTRACIÓN -- ============================================================
CREATE TABLE administrador_sistema ( id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), id_carrera UUID, CONSTRAINT fk_admin_sistema_carrera FOREIGN KEY (id_carrera) REFERENCES carrera(id) );
CREATE TABLE administrador_de_carrera ( id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), id_usuario UUID, id_carrera UUID, estado VARCHAR(100), fecha_registro DATE, CONSTRAINT fk_admin_carrera_usuario FOREIGN KEY (id_usuario) REFERENCES usuario(usuario_id), CONSTRAINT fk_admin_carrera_carrera FOREIGN KEY (id_carrera) REFERENCES carrera(id) );
CREATE TABLE tipo_reporte ( id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), nombre VARCHAR(250), descripcion VARCHAR(250), disponibilidad BOOLEAN );
CREATE TABLE reporte ( id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), id_administrador UUID, id_tipo_reporte UUID, id_carrera UUID, fecha_creacion DATE, formato VARCHAR(20), archivo_url TEXT, CONSTRAINT fk_reporte_administrador FOREIGN KEY (id_administrador) REFERENCES administrador_de_carrera(id), CONSTRAINT fk_reporte_tipo FOREIGN KEY (id_tipo_reporte) REFERENCES tipo_reporte(id), CONSTRAINT fk_reporte_carrera FOREIGN KEY (id_carrera) REFERENCES carrera(id) );
CREATE TABLE encuesta ( id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), id_administrador UUID, id_carrera UUID, titulo VARCHAR(250), fecha_inicio DATE, fecha_fin DATE, estado VARCHAR(20), fecha_creacion DATE, formato VARCHAR(100), direccion_url TEXT, CONSTRAINT fk_encuesta_administrador FOREIGN KEY (id_administrador) REFERENCES administrador_de_carrera(id), CONSTRAINT fk_encuesta_carrera FOREIGN KEY (id_carrera) REFERENCES carrera(id) );
-- ============================================================ -- SECCIÓN: EMPRESAS -- ============================================================
CREATE TABLE empresa ( id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), id_usuario UUID, razon_social VARCHAR(100), NIT VARCHAR(20), descripcion VARCHAR(255), correo VARCHAR(255), sitio_web VARCHAR(45), fecha_registro TIMESTAMP, CONSTRAINT fk_empresa_usuario FOREIGN KEY (id_usuario) REFERENCES usuario(usuario_id) );
CREATE TABLE telefono_empresa ( id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), id_empresa UUID, numero VARCHAR(20), tipo VARCHAR(50), CONSTRAINT fk_telefono_empresa FOREIGN KEY (id_empresa) REFERENCES empresa(id) );
CREATE TABLE sector_empresa ( id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), id_empresa UUID, nombre VARCHAR(100), descripcion VARCHAR(255), estado VARCHAR(20), CONSTRAINT fk_sector_empresa FOREIGN KEY (id_empresa) REFERENCES empresa(id) );
CREATE TABLE direccion_empresa ( id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), id_empresa UUID, departamento VARCHAR(100), direccion VARCHAR(255), CONSTRAINT fk_direccion_empresa FOREIGN KEY (id_empresa) REFERENCES empresa(id) );
CREATE TABLE perfil_empresa ( id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), id_empresa UUID, nombre VARCHAR(100), apellido VARCHAR(100), correo VARCHAR(255), contrasenia VARCHAR(255), cargo VARCHAR(100), estado VARCHAR(20), fecha_creacion TIMESTAMP, CONSTRAINT fk_perfil_empresa FOREIGN KEY (id_empresa) REFERENCES empresa(id) );
-- ============================================================ -- SECCIÓN: EGRESADOS -- ============================================================
CREATE TABLE egresado ( id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), id_descripcion UUID, apellido VARCHAR(45), cod_sis NUMERIC, id_carrera UUID, ci VARCHAR(20), extension_ci VARCHAR(20), anio_ingreso SMALLINT, grado VARCHAR(45), CONSTRAINT fk_egresado_carrera FOREIGN KEY (id_carrera) REFERENCES carrera(id) );
CREATE TABLE curriculum_vitae ( id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), id_egresado UUID UNIQUE, id_tipo_archivo UUID, ruta TEXT, valido BOOLEAN, CONSTRAINT fk_cv_egresado FOREIGN KEY (id_egresado) REFERENCES egresado(id), CONSTRAINT fk_cv_tipo_archivo FOREIGN KEY (id_tipo_archivo) REFERENCES tipo_archivo(id) );
CREATE TABLE formacion_academica ( id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), id_egresado UUID, institucion VARCHAR(150) NOT NULL, titulo VARCHAR(150) NOT NULL, anio_egreso SMALLINT NOT NULL, fecha_creacion TIMESTAMP DEFAULT NOW(), CONSTRAINT fk_formacion_egresado FOREIGN KEY (id_egresado) REFERENCES egresado(id) );
CREATE TABLE experiencia_laboral ( id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), id_egresado UUID, empresa VARCHAR(150) NOT NULL, cargo VARCHAR(100) NOT NULL, fecha_inicio DATE NOT NULL, fecha_fin DATE, fecha_creacion TIMESTAMP DEFAULT NOW(), CONSTRAINT fk_experiencia_egresado FOREIGN KEY (id_egresado) REFERENCES egresado(id) );
CREATE TABLE certificacion ( id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), id_egresado UUID, nombre VARCHAR(150) NOT NULL, entidad_emisora VARCHAR(150) NOT NULL, grado VARCHAR(50) NOT NULL, anio_emision SMALLINT, fecha_creacion TIMESTAMP, CONSTRAINT fk_certificacion_egresado FOREIGN KEY (id_egresado) REFERENCES egresado(id) );
CREATE TABLE certificacion_respaldo ( id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), id_certificacion UUID, tipo VARCHAR(20) NOT NULL CHECK (tipo IN ('FOTO','QR','DOCUMENTO')), archivo_key VARCHAR(255) NOT NULL, fecha_subida TIMESTAMP, CONSTRAINT fk_respaldo_certificacion FOREIGN KEY (id_certificacion) REFERENCES certificacion(id) ON DELETE CASCADE );
CREATE TABLE perfil_area ( id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), area_id UUID, id_egresado UUID, descripcion_profesional TEXT, fecha_creacion DATE, fecha_actualizacion DATE, CONSTRAINT fk_perfil_area_area FOREIGN KEY (area_id) REFERENCES area(id), CONSTRAINT fk_perfil_area_egresado FOREIGN KEY (id_egresado) REFERENCES egresado(id) );
-- ============================================================ -- SECCIÓN: MENTORING -- ============================================================
CREATE TABLE mentor ( id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), experiencia TEXT, esta_activo BOOLEAN, anios_exp INTEGER, fecha_creacion DATE, fecha_actualizacion DATE );
CREATE TABLE mentor_area ( id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), id_mentor UUID, id_area UUID, fecha_creacion DATE, CONSTRAINT fk_mentor_area_mentor FOREIGN KEY (id_mentor) REFERENCES mentor(id), CONSTRAINT fk_mentor_area_area FOREIGN KEY (id_area) REFERENCES area(id) );
CREATE TABLE disponibilidad_mentor ( id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), id_mentor UUID, estado VARCHAR(20), fecha_creacion DATE, fecha_actualizacion DATE, hora_inicio TIME, hora_fin TIME, CONSTRAINT fk_disponibilidad_mentor FOREIGN KEY (id_mentor) REFERENCES mentor(id) );
CREATE TABLE espacio_disponible_mentor ( id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), id_mentor UUID, dia_semana SMALLINT, horario_inicio TIME, horario_fin TIME, esta_activo BOOLEAN, fecha_creacion DATE, fecha_actualizacion DATE, CONSTRAINT fk_espacio_mentor FOREIGN KEY (id_mentor) REFERENCES mentor(id) );
CREATE TABLE mentoria_solicitud ( id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), id_mentor UUID, id_usuario UUID, solicitud_fecha DATE, solicitud_inicio TIME, solicitud_fin TIME, mensaje TEXT, estado VARCHAR(20), fecha_respuesta DATE, fecha_creacion DATE, fecha_actualizacion DATE, CONSTRAINT fk_mentoria_solicitud_mentor FOREIGN KEY (id_mentor) REFERENCES mentor(id), CONSTRAINT fk_mentoria_solicitud_usuario FOREIGN KEY (id_usuario) REFERENCES usuario(usuario_id) );
CREATE TABLE conexion ( id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), id_mentoria_solicitud UUID, estado VARCHAR(20), fecha_inicio DATE, fecha_fin DATE, fecha_creacion DATE, fecha_actualizacion DATE, CONSTRAINT fk_conexion_mentoria FOREIGN KEY (id_mentoria_solicitud) REFERENCES mentoria_solicitud(id) );
CREATE TABLE sesion ( id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), id_conexion UUID, fecha_programada DATE, tiempo_inicio TIME, tiempo_fin TIME, estado VARCHAR(20), url_reunion VARCHAR(500), fecha_creacion DATE, fecha_actualizacion DATE, CONSTRAINT fk_sesion_conexion FOREIGN KEY (id_conexion) REFERENCES conexion(id) );
-- ============================================================ -- SECCIÓN: REQUERIMIENTOS LABORALES Y VACANTES -- ============================================================
CREATE TABLE requerimiento_laboral ( id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), id_empresa UUID, id_modalidad UUID, titulo VARCHAR(45), descripcion TEXT, experiencia_requerida VARCHAR(100), ubicacion VARCHAR(45), fecha_publicacion TIMESTAMP, fecha_cierre TIMESTAMP, estado VARCHAR(20), CONSTRAINT fk_requerimiento_empresa FOREIGN KEY (id_empresa) REFERENCES empresa(id), CONSTRAINT fk_requerimiento_modalidad FOREIGN KEY (id_modalidad) REFERENCES modalidad_trabajo(id) );
CREATE TABLE requerimiento_habilidad ( id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), id_area UUID, id_requerimiento UUID, nivel_requerimiento VARCHAR(20), CONSTRAINT fk_req_habilidad_area FOREIGN KEY (id_area) REFERENCES area(id), CONSTRAINT fk_req_habilidad_requerimiento FOREIGN KEY (id_requerimiento) REFERENCES requerimiento_laboral(id) );
CREATE TABLE vacante ( id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), id_empresa UUID, titulo VARCHAR(150), salario DECIMAL(10,2), modalidad VARCHAR(50), estado VARCHAR(30), created_at TIMESTAMP, CONSTRAINT fk_vacante_empresa FOREIGN KEY (id_empresa) REFERENCES empresa(id) );
CREATE TABLE vacante_requerimiento_laboral ( id_vacante UUID, id_requerimiento_laboral UUID, PRIMARY KEY (id_vacante, id_requerimiento_laboral), CONSTRAINT fk_vac_req_vacante FOREIGN KEY (id_vacante) REFERENCES vacante(id), CONSTRAINT fk_vac_req_requerimiento FOREIGN KEY (id_requerimiento_laboral) REFERENCES requerimiento_laboral(id) );
CREATE TABLE postulacion ( id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), id_usuario UUID, id_vacante UUID, porcentaje_match DECIMAL(5,2), estado VARCHAR(20), created_at TIMESTAMP, CONSTRAINT fk_postulacion_usuario FOREIGN KEY (id_usuario) REFERENCES usuario(usuario_id), CONSTRAINT fk_postulacion_vacante FOREIGN KEY (id_vacante) REFERENCES vacante(id) );
-- ============================================================ -- SECCIÓN: EVENTOS -- ============================================================
CREATE TABLE evento ( id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), id_usuario UUID, titulo VARCHAR(45), descripcion TEXT, fecha_inicio TIMESTAMPTZ, fecha_fin TIMESTAMPTZ, cupo_maximo INTEGER, ubicacion VARCHAR(100), estado VARCHAR(30), imagen_url TEXT, fecha_creacion TIMESTAMPTZ, CONSTRAINT fk_evento_usuario FOREIGN KEY (id_usuario) REFERENCES usuario(usuario_id) );
CREATE TABLE inscripcion_evento ( id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), id_evento UUID, id_usuario UUID, fecha_inscripcion TIMESTAMPTZ, estado VARCHAR(20), CONSTRAINT fk_inscripcion_evento FOREIGN KEY (id_evento) REFERENCES evento(id), CONSTRAINT fk_inscripcion_usuario FOREIGN KEY (id_usuario) REFERENCES usuario(usuario_id) );
-- ============================================================ -- SECCIÓN: SOLICITUDES Y DOCUMENTOS -- ============================================================
CREATE TABLE detalle_solicitud ( id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), id_carrera UUID, nombre VARCHAR(45), apellido VARCHAR(45), telefono VARCHAR(20), email VARCHAR(255), fecha_titulacion DATE, fecha_ingreso DATE, ci VARCHAR(20), extension_ci VARCHAR(20), anio_egreso SMALLINT, cod_sis NUMERIC, desea_mentor BOOLEAN, CONSTRAINT fk_detalle_solicitud_carrera FOREIGN KEY (id_carrera) REFERENCES carrera(id) );
CREATE TABLE documento_respaldo ( id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), id_tipo_archivo UUID, tamanio_mb INTEGER, ruta_storage TEXT, fecha_creacion TIMESTAMP, es_valido BOOLEAN, CONSTRAINT fk_documento_tipo_archivo FOREIGN KEY (id_tipo_archivo) REFERENCES tipo_archivo(id) );
CREATE TABLE solicitud ( id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), id_detalle_solicitud UUID, id_documento_respaldo UUID, estado VARCHAR(20), fecha_creacion TIMESTAMP, CONSTRAINT fk_solicitud_detalle FOREIGN KEY (id_detalle_solicitud) REFERENCES detalle_solicitud(id), CONSTRAINT fk_solicitud_documento FOREIGN KEY (id_documento_respaldo) REFERENCES documento_respaldo(id) );
CREATE TABLE usuario_solicitud ( id_usuario UUID, id_solicitud UUID, detalle_solicitud_id UUID, PRIMARY KEY (id_usuario, id_solicitud), CONSTRAINT fk_usuario_sol_usuario FOREIGN KEY (id_usuario) REFERENCES usuario(usuario_id), CONSTRAINT fk_usuario_sol_solicitud FOREIGN KEY (id_solicitud) REFERENCES solicitud(id), CONSTRAINT fk_usuario_sol_detalle FOREIGN KEY (detalle_solicitud_id) REFERENCES detalle_solicitud(id) );
CREATE TABLE dictamen ( id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), id_administrador_sistema UUID, id_solicitud UUID, justificacion TEXT, fecha_creacion TIMESTAMP, fecha_actualizacion DATE, subsanada BOOLEAN, CONSTRAINT fk_dictamen_admin_sistema FOREIGN KEY (id_administrador_sistema) REFERENCES administrador_sistema(id), CONSTRAINT fk_dictamen_solicitud FOREIGN KEY (id_solicitud) REFERENCES solicitud(id) );
-- ============================================================ -- SECCIÓN: NOTIFICACIONES -- ============================================================
CREATE TABLE notificacion ( id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), id_usuario UUID, id_vacante UUID, tipo_mensaje VARCHAR(200), leida BOOLEAN, created_at TIMESTAMP, CONSTRAINT fk_notificacion_usuario FOREIGN KEY (id_usuario) REFERENCES usuario(usuario_id), CONSTRAINT fk_notificacion_vacante FOREIGN KEY (id_vacante) REFERENCES vacante(id) );
CREATE TABLE dispositivo ( id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), usuario_id UUID, url_push TEXT, llave_publica TEXT, llave_secreta TEXT, navegador VARCHAR(100), plataforma VARCHAR(50), fecha_creacion TIMESTAMP, fecha_actualizacion TIMESTAMP, CONSTRAINT fk_dispositivo_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(usuario_id) );
-- ============================================================ -- SECCIÓN: MENSAJERÍA Y CONVERSACIONES -- ============================================================
CREATE TABLE conversacion ( id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), tipo VARCHAR(20), nombre VARCHAR(100), estado_conversacion VARCHAR(20), creado_por UUID, fecha_creacion TIMESTAMP, fecha_actualizacion TIMESTAMP, CONSTRAINT fk_conversacion_creador FOREIGN KEY (creado_por) REFERENCES usuario(usuario_id) );
CREATE TABLE participante_conversacion ( id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), conversacion_id UUID, usuario_id UUID, rol_en_chat VARCHAR(20), fecha_union DATE, CONSTRAINT fk_participante_conversacion FOREIGN KEY (conversacion_id) REFERENCES conversacion(id), CONSTRAINT fk_participante_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(usuario_id) );
CREATE TABLE mensaje ( id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), id_conversacion UUID, emisor_id UUID, contenido TEXT, tipo_contenido VARCHAR(50), archivo_url TEXT, estado_envio VARCHAR(20), fecha_mensaje TIMESTAMP, CONSTRAINT fk_mensaje_conversacion FOREIGN KEY (id_conversacion) REFERENCES conversacion(id), CONSTRAINT fk_mensaje_emisor FOREIGN KEY (emisor_id) REFERENCES usuario(usuario_id) );
CREATE TABLE mensaje_estado ( id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), id_mensaje UUID, usuario_id UUID, estado VARCHAR(20), fecha TIMESTAMP, CONSTRAINT fk_mensaje_estado_mensaje FOREIGN KEY (id_mensaje) REFERENCES mensaje(id), CONSTRAINT fk_mensaje_estado_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(usuario_id) );
-- ============================================================ -- FIN DEL SCRIPT -- ============================================================